#配置数据源
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.0.111:3306/study
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.0.112:3306/study
      username: read   # 只读账户
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.0.113:3306/study
      username: read2   # 只读账户
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver